org: dcttechnology
service: event-driven-notification-system

custom:
  eventBusName: app-event-bus

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev
  environment:
    EVENT_BUS_NAME: ${self:custom.eventBusName}
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  eventPublisher:
    handler: handler.publishEvent
    events:
      - httpApi:
          path: /event
          method: post

  emailConsumer:
    handler: handler.emailConsumer

  analyticsConsumer:
    handler: handler.analyticsConsumer

  logConsumer:
    handler: handler.logConsumer

resources:
  Resources:
    UserSignupRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName:
          Ref: EventBus
        EventPattern:
          source:
            - "app.user"
          detail-type:
            - "USER_SIGNUP"
        Targets:
          - Arn:
              Fn::GetAtt: [EmailConsumerLambdaFunction, Arn]
            Id: "EmailTarget"

          - Arn:
              Fn::GetAtt: [AnalyticsConsumerLambdaFunction, Arn]
            Id: "AnalyticsTarget"

          - Arn:
              Fn::GetAtt: [LogConsumerLambdaFunction, Arn]
            Id: "LogTarget"

    EmailPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: EmailConsumerLambdaFunction
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com

    AnalyticsPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: AnalyticsConsumerLambdaFunction
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com

    LogPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: LogConsumerLambdaFunction
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com

    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBusName}
